import AbstractRuntime from '../runtimes/interface';
import Channels from './channels/channels';
import Channel from './channels/channel';
import { default as EventsDispatcher } from './events/dispatcher';
import Timeline from './timeline/timeline';
import TimelineSender from './timeline/timeline_sender';
import ConnectionManager from './connection/connection_manager';
import { PeriodicTimer } from './utils/timers';
import { Options } from './options';
import { Config } from './config';
import UserFacade from './user';
import DeltaCompressionManager from './delta/manager';
import { DeltaStats } from './delta/types';
import { Filter, validateFilter, FilterExamples } from './channels/filter';
import type { FilterNode } from './channels/filter';
import type { RecoveryPosition } from './connection/protocol/message-types';
import type { ChannelSubscriptionOptions } from './channels/channel';
export { Filter, validateFilter, FilterExamples };
export type { FilterNode };
export default class Pusher {
    static instances: Pusher[];
    static isReady: boolean;
    private static _logToConsole;
    private static _log;
    static get logToConsole(): boolean;
    static set logToConsole(value: boolean);
    static get log(): ((message: any) => void) | undefined;
    static set log(fn: ((message: any) => void) | undefined);
    static Runtime: AbstractRuntime;
    static ScriptReceivers: any;
    static DependenciesReceivers: any;
    static auth_callbacks: any;
    static ready(): void;
    private static getClientFeatures;
    key: string;
    config: Config;
    channels: Channels;
    global_emitter: EventsDispatcher;
    sessionID: number;
    timeline: Timeline;
    timelineSender: TimelineSender;
    connection: ConnectionManager;
    timelineSenderTimer: PeriodicTimer;
    user: UserFacade;
    deltaCompression: DeltaCompressionManager;
    constructor(app_key: string, options: Options);
    channel(name: string): Channel;
    allChannels(): Channel[];
    connect(): void;
    disconnect(): void;
    bind(event_name: string, callback: Function, context?: any): Pusher;
    unbind(event_name?: string, callback?: Function, context?: any): Pusher;
    bind_global(callback: Function): Pusher;
    unbind_global(callback?: Function): Pusher;
    unbind_all(callback?: Function): Pusher;
    subscribeAll(): void;
    subscribe(channel_name: string, options?: any | ChannelSubscriptionOptions): Channel;
    unsubscribe(channel_name: string): void;
    send_event(event_name: string, data: any, channel?: string): boolean;
    shouldUseTLS(): boolean;
    signin(): void;
    getDeltaStats(): DeltaStats | null;
    resetDeltaStats(): void;
    getRecoveryPosition(channelName: string): RecoveryPosition | null;
    getRecoveryPositions(): Record<string, RecoveryPosition>;
    setRecoveryPosition(channelName: string, position: RecoveryPosition | null): void;
    setRecoveryPositions(positions: Record<string, RecoveryPosition>): void;
}
